services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/user?authSource=admin #mongodb instead of localhost
    networks:
      - app-network

  mongodb:
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_DATABASE=user
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
